// <auto-generated />
using System;
using BookExchange.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookExchange.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111130447_FinalModelSetup")]
    partial class FinalModelSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Book.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookId");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Author");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("ISBN");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusKey");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Domain.ExchangeRequest.ExchangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestId");

                    b.Property<Guid>("BookOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookOwnerId");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ExchangeMethod");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RecipientId");

                    b.Property<Guid>("RequestedBookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestedBookId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusKey");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRequests", (string)null);
                });

            modelBuilder.Entity("Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.ExchangeRequest.ExchangeRequest", b =>
                {
                    b.OwnsOne("Domain.ExchangeRequest.VO.ExchangeHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("ExchangeRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Events")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ExchangeEvents");

                            b1.HasKey("ExchangeRequestId");

                            b1.ToTable("ExchangeRequests");

                            b1.WithOwner()
                                .HasForeignKey("ExchangeRequestId");
                        });

                    b.Navigation("History")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.User.User", b =>
                {
                    b.OwnsOne("Domain.User.VO.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Phone");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.User.VO.UserRating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Rating")
                                .HasColumnType("float")
                                .HasColumnName("RatingValue");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("Domain.User.VO.Review", "Reviews", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("Date")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ReviewDate");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("ReviewText");

                                    b2.Property<Guid?>("UserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("UserReviews", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("Reviews");
                        });

                    b.OwnsOne("Domain.User.VO.WishList", "WishList", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("Domain.Book.VO.BookId", "Books", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("UserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("BookId");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("WishListItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("Books");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("WishList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
